<?php

/**
 * @file
 * This is the main module for EZAC - Leden
 *
 */
 
    /**
    * @defgroup Ezac
    * @{
    *
    * @todo Insert usage examples
    */

    /**
     * @} End of "defgroup Ezac".
     */

/**
* Implements hook_theme()
*/
function ezac_leden_theme() {
 return [
     'ezac_leden_update_form' => [
         'render element'   => 'form',
         'template'         => 'ezac_leden_update_form',
    ],
 ];
}

