<?php

/**
 * @file
 * This is the main module for EZAC - Leden
 *
 */
 
    /**
    * @defgroup ezac
    * @{
    *
    * @todo Insert usage examples
    */

    /**
     * @} End of "defgroup ezac".
     */

/**
* Implements hook_theme()
*/
function ezacLeden_theme() {
 return [
     'ezac_leden_update_form' => [
         'render element'   => 'form',
         'template'         => 'ezac_leden_update_form',
         'base hook'        => 'form',
    ],
 ];
}

/**
 * Implements hook_theme_suggestions_alter().
 * taken from https://drupal.stackexchange.com/questions/216134/custom-form-using-custom-template-submit-the-form-dont-call-its-validate-and-s
 */
function ezacLeden_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {

    if ($hook == 'form' & !empty($variables['element']['#theme'])) {
        $suggestions[] = 'form__' . $variables['element']['#theme'][0];
    }
}

/**
 * @param array $suggestions
 * @param array $variables
 * @return array
 *
 * alternative from https://www.foreach.be/blog/how-manipulate-forms-drupal-8?lang=nl

function form_overwrite_theme_suggestions_alter(array &$suggestions, array $variables)
{

    if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
        $original_theme_hook = $variables['theme_hook_original'];

        $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
    }

    return $suggestions;

}
 */

